module HangmanWords where

hangmanWords :: [[Char]]
hangmanWords = ["ABLE","ABOUT","ABOVE","ACROSS","ACT","AFRAID","AFTER",
 "AFTERNOON","AGAIN","AGAINST","AGE","AGO","AIR","AIRPLANE","AIRPORT","ALBUM",
 "ALL","ALMOST","ALONE","ALONG","ALREADY","ALSO","ALWAYS","AMONG",
 "ANGRY","ANIMAL","ANOTHER","ANSWER","ANY","ANYBODY","ANYONE","ANYTHING",
 "APARTMENT","APPLE","APRIL","ARM","AROUND","ARRIVE","ARTIST","ASK","ATTACK",
 "AUGUST","AUTUMN","AWAY",
 
 "BABY","BACK","BAD","BAG","BALL","BANANA","BANK","BASEBALL","BASKETBALL",
 "BATHROOM","BEAUTIFUL","BECAUSE","BECOME","BEDROOM","BEFORE","BEGIN","BEHIND",
 "BELIEVE","BELOW","BENCH","BESIDE","BEST","BETTER","BETWEEN","BICYCLE",
 "BIG","BIKE","BIRD","BIRTHDAY","BLACK","BLOW","BLUE","BOAT","BODY","BOOK",
 "BORN","BOTH","BOTTLE","BOX","BOY","BREAK","BRIDGE","BRING","BROTHER","BROWN",
 "BUILD","BUS","BUSINESS","BUSY","BUT","BUY",
 
 "CAKE","CALENDAR","CALL","CAMERA","CAMP","CANDY","CAR","CARD","CAREFUL",
 "CARRY","CASE","CAT","CATCH","CENTER","CHAIR","CHANCE","CHANGE","CHEAP",
 "CHEESE","CHICKEN","CHILD","CHILDREN","CHOCOLATE","CHOOSE","CHRISTMAS",
 "CHURCH","CIRCLE","CITY","CLASS","CLEAN","CLEAR","CLEVER","CLOCK","CLOSE",
 "CLOUD","CLOUDY","COFFEE","COLD","COLLEGE","COLOR","COME","COMPANY","COOK",
 "COOKIE","COOL","CORNER","COULD","COUNT","COUNTRY","COVER","CRY","CUT",
 
 "DANCE","DANGEROUS","DARK","DATE","DAUGHTER","DAY","DEAD","DEAR","DEATH",
 "DECEMBER","DECIDE","DEEP","DELICIOUS","DEPARTMENT","DESK","DIARY",
 "DICTIONARY","DIE","DIFFERENT","DIFFICULT","DINNER","DISCOVER","DOCTOR","DOG",
 "DOOR","DOWN","DRAW","DREAM","DRINK","DRIVE","DRIVER","DROP","DURING",
 
 "EACH","EAR","EARLY","EARTH","EASY","EAT","EIGHT","EITHER","ELEPHANT","ELEVEN",
 "ELSE","END","ENJOY","ENOUGH","ENTER","EVEN","EVER","EVERY","EVERYBODY",
 "EVERYONE","EVERYTHING","EXCUSE","EYE",

 "FACE","FACT","FACTORY","FALL","FAMILY","FAMOUS","FAST","FATHER","FEBRUARY",
 "FEEL","FEW","FIELD","FIGHT","FILM","FIND","FINE","FINGER","FINISH","FIRE",
 "FIRST","FISH","FIVE","FLOOR","FLOWER","FLY","FOOL","FOOTBALL","FOREST",
 "FOUR","FREE","FRESH","FRIDAY","FRIEND","FRONT","FULL","FUN","FUTURE",

 "GAME","GARDEN","GENTLEMAN","GET","GIRL","GIVE","GLAD","GLASS","GLOVE","GO",
 "GOAL","GOD","GOLD","GOLF","GOOD","GRANDFATHER","GRANDMOTHER","GRASS","GREAT",
 "GREEN","GROUND","GROUP","GROW","GUEST","GUIDE","GUN",

 "HAIR","HALF","HAND","HAPPEN","HAPPINESS","HAPPY","HARD","HAT","HAVE","HEAD",
 "HEAR","HEAVY","HELLO","HELP","HERE","HIGH","HISTORY","HOLD","HOLIDAY","HOME",
 "HOMEWORK","HONEST","HONEY","HOPE","HORSE","HOSPITAL","HOTEL","HOUR","HOUSE",
 "HOW","HUNDRED","HUNGRY","HURRY","HUSBAND",

 "ICE","IDEA","IMPORTANT","INSIDE","INTERESTING","INTO","ISLAND",

 "JANUARY","JOB","JOIN","JUICE","JULY","JUMP","JUNE","JUST",

 "KEEP","KEY","KICK","KILL","KIND","KING","KISS","KITCHEN","KNIFE","KNOW",

 "LADY","LAKE","LAND","LANGUAGE","LARGE","LAST","LATE","LATER","LAUGH","LEAF",
 "LEARN","LEAVE","LEFT","LEG","LESSON","LETTER","LEVEL","LIBRARY","LIFE",
 "LIGHT","LIKE","LINE","LION","LIST","LISTEN","LITTLE","LIVE","LONG","LOOK",
 "LOSE","LOVE","LOW","LUCKY","LUNCH",

 "MACHINE","MAGAZINE","MAIL","MAKE","MAN","MANY","MAP","MARCH","MARKET",
 "MARRY","MASTER","MATTER","MAY","ME","MEAN","MEAT","MEET","MEETING","MEMBER",
 "MEMORY","MEN","MIDDLE","MIDNIGHT","MILK","MIND","MINE","MINUTE","MIRROR",
 "MISS","MISTAKE","MONDAY","MONEY","MONKEY","MONTH","MOON","MORE","MORNING",
 "MOST","MOTHER","MOUNTAIN","MOUSE","MOUTH","MOVE","MOVIE","MUCH","MUSIC",
 "MUST",

 "NAME","NARROW","NATURAL","NEAR","NECESSARY","NEED","NEIGHBOR","NEVER",
 "NEW","NEWS","NEXT","NICE","NIGHT","NINE","NOBODY","NOISE","NONE","NOON",
 "NORTH","NOSE","NOT","NOTEBOOK","NOTHING","NOVEMBER","NOW","NUMBER",

 "OCTOBER","OFF","OFFICE","OFTEN","OLD","ONCE","ONE","ONLY","OPEN","ORANGE",
 "ORDER","OTHER","OUR","OTSIDE","OVER",

 "PAGE","PAINT","PAIR","PAPER","PARENT","PARK","PARTY","PASS","PAY","PEN",
 "PENCIL","PEOPLE","PERCENT","PERHAPS","PERSON","PHONE","PHOTOGRAPH","PIANO",
 "PICK","PICNIC","PICTURE","PIECE","PIG","PILOT","PINK","PLACE","PLAN","PLANE",
 "PLAY","PLEASE","POCKET","POINT","POLICE","POOL","POOR","POPULAR","POST",
 "POTATO","POWER","POUND","PRACTICE","PRESENT","PRICE","PROMISE","PULL",
 "PUSH","PUT",

 "QUEEN","QUESTION","QUIZ","QUICK","QUIET",

 "RABBIT","RADIO","RAIN","RAINY","REACH","READ","READY","REAL","REALLY",
 "RECEIVE","RED","REMEMBER","RESTAURANT","RETURN","RICE","RICH","RIDE","RIGHT",
 "RING","RISE","RIVER","ROAD","ROBOT","ROCK","ROCKET","ROOF","ROOM","ROPE",
 "ROSE","ROUND","RULE","RUN",

 "SAFE","SALE","SAME","SAND","SANDWICH","SATURDAY","SAVE","SAY","SCENE",
 "SCHOOL","SCIENCE","SEA","SEASON","SEAT","SECOND","SECRET","SEE","SEEM",
 "SELL","SEND","SEPTEBER","SET","SEVEN","SEVERAL","SHALL","SHAPE","SHARP",
 "SHE","SHEEP","SHINE","SHIP","SHIRT","SHOP","SHORT","SHOULD","SHOW","SICK",
 "SIDE","SIGN","SILENT","SILVER","SIMPLE","SINCE","SING","SINGER","SISTER",
 "SIX","SIZE","SKI","SKY","SLEEP","SLOW","SMALL","SMELL","SMILE","SMOKE",
 "SNAKE","SNOW","SOCCER","SODA","SOFT","SOME","SOMEBODY","SOMEONE","SOMETHING",
 "SOMETIMES","SON","SONG","SOON","SORRY","SOUND","SOUTH","SPACE","SPEAK",
 "SPECIAL","SPEED","SPEND","SPOON","SPORT","SPRING","SQUARE","STAMP","STAND",
 "STAR","START","STATION","STAY","STEP","STILL","STONE","STOP","STORE","STORY",
 "STRAIGHT","STRANGE","STREET","STRONG","STUDENT","STUDY","SUBWAY","SUCH",
 "SUDDENLY","SUGAR","SUMMER","SUN","SUNDAY","SUPERMARLET","SURE","SUPRISE",
 "SWEET","SWIM","SWITCH",

 "TABLE","TAKE","TALK","TALL","TAPE","TASTE","TEA","TEACH","TEACHER","TEAM",
 "TELEPHONE","TELEVISION","TELL","TEN","TENNIS","TEST","TEXTBOOK","THAN",
 "THANK","THAT","THE","THEIR","THEM","THEN","THERE","THESE","THEY","THING",
 "THINK","THIRD","THIS","THOSE","THOUGH","THOUSAND","THREE","THROW",
 "THURSDAY","TICKET","TIGER","TIME","TIRED","TODAY","TOGETHER","TOILET",
 "TOMATO","TOMORROW","TONIGHT","TOO","TOOTH","TOP","TOUCH","TOWARD","TOWER",
 "TOWN","TOY","TRAIN","TRAVEL","TREE","TRIP","TROUBLE","TRUE","TRY","TUESDAY",
 "TURN","TWELVE","TWO","TYPE",

 "UMBRELLA","UNDER","UNDERSTAND","USE","USEFUL","USUALLY",

 "VACATION","VEGETABLE","VERY","VIDEO","VILLAGE","VIOLIN","VISIT","VISITOR",
 "VOICE",

 "WAIT","WAKE","WALK","WALL","WANT","WAR","WARM","WASH","WATCH","WATER","WAVE",
 "WAY","WEAK","WEAR","WEDNESDAY","WEEK","WEEKND","WELCOME","WELL","WEST",
 "WHAT","WHEN","WHERE","WHICH","WHILE","WHITE","WHO","WHOSE","WHY","WIDE",
 "WIFE","WILD","WILL","WIND","WINDOW","WINE","WINTER","WISE","WITH","WITHOUT",
 "WOMAN","WONDERFUL","WOOD","WORK","WORLD","WORST","WOULD","WRITE","WRONG",

 "YEAR","YELLOW","YES","YESTERDAY","YOU","YOUNG","YOUR",

 "ZOO","ZERO"
 ]
